### ISSUE TITLE
Loading issue on Old 3DS

### ISSUE THREAD

**Issue by Candy42FNaC** [erievs/FourthTube#11]
(Old 3DS) When loading the homepage, it completely froze until it said "[home] Connection timeout after 300442 ms" on the homepage
If it is a performance issue i wanted to report it.
Thank you.

**Comment by erievs** [comment]
i don't think it is a performance issue or anything, people have been able to load it on an old 3ds sadly there's not much i can do for you as i don't own an old 3ds
