### ISSUE TITLE
No easy way to view recent streams on a channel

### ISSUE THREAD

**Issue by bitlamas** [erievs/FourthTube#20]
For content creators who primarily stream their videos, there's currently no straightforward method to view their latest streams on the 3DS app. While these streams are accessible under the "Live" tab on the desktop app, the 3DS app only offers Videos, Playlists, Community, and Info tabs.

If I want to watch the latest videos of these streamer channels I must search for specific video titles instead. I believe it would be beneficial to implement a feature that allows easy access to recent streams within the 3DS app, maybe add an extra tab "Live" like it is in the desktop.

**Comment by bimmy4664** [comment]
Same thing applies to Shorts as well.
Maybe we should combine all of them together (just like how YouTube did it before).

**Comment by erievs** [comment]
maybe at some point but not a feature I feel like adding in the sort term
