### ISSUE TITLE
Video ends 2 seconds early and immediately autoplays to the next video

### ISSUE THREAD

**Issue by bimmy4664** [erievs/FourthTube#22]
TL;DR: Title

I'm on Beta 22 and using an old 3DS.
Maybe autoplay can be an option in a future update?

**Comment by Macflylegamer** [comment]
There's already an autoplay option in Playback tab on Settings
![IMG_20240922_222305](https://github.com/user-attachments/assets/0d2b16a9-0fd0-43f7-8a28-5dd6b3b98966)

**Comment by erievs** [comment]
not an issue and the feature is already in

**Comment by bimmy4664** [comment]
Oh, I didn't know Autoplay was enabled by default in FourthTube.

But when it is enabled, the video still ends 2 seconds early. This is definitely an issue to me.
