### ISSUE TITLE
Feature Request: 480p support (New3DS users)

### ISSUE THREAD

**Issue by DragonWario** [erievs/FourthTube#30]
Since the resolution of YouTube 480p is 854x480, it may be possible for some videos to work at this quality considering the current performance of https://github.com/Core-2-Extreme/Video_player_for_3DS (which this is based on) in my own testing. It may not work for every video, but I think it would be neat to have the option as a "Your mileage may vary" option. Thanks again for reviving this project :)

**Comment by erievs** [comment]
uhhh yeah I will try at some point

**Comment by erievs** [comment]
Done! Thanks to 2ipper!
