### ISSUE TITLE
Crashes to home menu after a few minutes of playback (Old 3DS)

### ISSUE THREAD

**Issue by GammaBoost** [erievs/FourthTube#31]
After maybe 20 minutes of playback, the app may freeze and it will then go to the home menu with this error:
![IMG_6856](https://github.com/user-attachments/assets/9050269e-bc8e-460e-baf2-b82a3f6ea305)

This might be related to the crashing issue on 0.5.4 of thirdtube that occurred after a much shorter period of time (10-60 seconds), which did not occur on 0.5.3.

**Comment by erievs** [comment]
try 144p and we don't really support the old 3ds that much this was an issue with the old thirdtube
