### ISSUE TITLE
240p in old3ds?

### ISSUE THREAD

**Issue by Gusnoob45** [erievs/FourthTube#37]
Hello, I would like to ask if in future updates it would be possible to watch videos in 240p or higher? in old3ds and 2dsold

**Comment by 2b-zipper** [comment]
Impossible due to the lower performance of old3ds compared to new3ds
For example, new3ds has 256MB ram, old3ds has only half of that

**Comment by 2b-zipper** [comment]
Impossible because old3ds is considerably less powerful than new3ds
For example, new3ds has 256MB RAM, while old3ds has only half of that

**Comment by erievs** [comment]
more than likely no
