### ISSUE TITLE
360p再生が不安定 / 360p video playback is choppy

### ISSUE THREAD

**Issue by LuMariGames** [erievs/FourthTube#39]
## 内容(日本語)
先に申し上げますと、私は現在旧バージョン([b25](https://github.com/erievs/FourthTube/releases/tag/b25))を使おうか悩むレベルで今回のバージョンは酷いです。
恐らくこれは[Video player for 3DS](https://github.com/Core-2-Extreme/Video_player_for_3DS)の仕様上しょうがないがと言えるかもしれません。(※1)
ですが、Old3DSで144p再生が困難になるのは流石におかしいと思い今回書くに至りました。
どうしてそこまで再生が困難かと言いますと、「フレームバッファ」が直ぐに無くなりやすい事が原因です。
下の「スクリーンショット」に実際の画像を貼っておきます。
そして、出来るだけ早めに480pが削除される事を期待しています。
(360pもハードウェアデコーダで処理出来れば一番楽ですがね)

## Contents (English)
First of all, I would like to say that this version is so bad that I am now wondering whether I should use the old version ([b25](https://github.com/erievs/FourthTube/releases/tag/b25)).
Perhaps this is due to the specification of [Video player for 3DS](https://github.com/Core-2-Extreme/Video_player_for_3DS).(*1)
However, I thought it was strange that 144p playback is so difficult on the Old 3DS, so I decided to write this article.
The reason why playback is so difficult is that the “frame buffer” tends to run out quickly.
The screenshots below are actual images.
And we hope that 480p will be removed as soon as possible.
(It would be easiest if 360p could also be processed by a hardware decoder.)

## スクリーンショット(Screenshots)
![2024-10-20_20-00-57 620_bot](https://github.com/user-attachments/assets/abe474ea-6be9-466b-b8b8-de15ae5ca40a)

※1:動画の画質を下げるにはソフト内デコードを使用するしか無い。
※1:The only way to lower the video quality is to use the software's built-in decoder.

**Comment by 2b-zipper** [comment]
本当にごめんなさい、適当に置き換えたせいで色々とミスしてました。
次のリリースで修正されると思います

**Comment by 2b-zipper** [comment]
Old3DSの問題も修正できているようです
beta 27を試してみてください

**Comment by LuMariGames** [comment]
無事治りました！ありがとう！
