### ISSUE TITLE
メモリリークが起きる可能性がある不具合(Possible memory leak issue)

### ISSUE THREAD

**Issue by LuMariGames** [erievs/FourthTube#4]
## 不具合内容 (日本語)
前方バッファが機能していない為、いくら待ってもその部分が削除されずに残り続けます。
そして、メモリリークを起こしクラッシュする不具合があります。
更にこの残り続けた前方バッファは動画を閉じたり別の動画を見ても残ります。
早めの修正を待っています。

## Problem details (English)
Because the forward buffer is not functioning, no matter how long you wait, the part will not be deleted and will remain.
And there is a problem that causes a memory leak and crashes.
Furthermore, this remaining forward buffer will remain even if you close the video or watch another video.
We are waiting for a quick fix.

## スクリーンショット(ScreenShot)
![screenshot_bottom](https://github.com/user-attachments/assets/b4e112f6-d79e-48d9-8807-6cb4992ee9c1)

**Comment by erievs** [comment]
English

Bingo

Thank you so much this will be very helpful!

日本語（Google翻訳）
ビンゴ
本当にありがとうございます、とても助かります！

**Comment by LuMariGames** [comment]
無事修正されたのを確認しました。
ありがとうございます！

I have confirmed that the issue has been fixed successfully. Thank you!
