### ISSUE TITLE
Videos won't load after loading 1 video

### ISSUE THREAD

**Issue by Maxbrick** [erievs/FourthTube#48]
So this just happened today for some reason.

Loading another video doesn't work after first one

Steps 2 reproduce:
load a video, then load another video. It will not load any video details; you must restart fourthtube to load another video.
Expected Behavior: Second video loads same as first.

Client Device Specifications:
New Nintendo 3DS
Luma 13.2
Load ext. game modules/firm : ON
Load game plugins: ON

P.S. I am opening this issue from my 3DS browser, no joke

**Comment by erievs** [comment]
Strange, I have the same setup (I am pretty sure same Luma version as well). Probably would be best to ask on the discord server.

**Comment by Maxbrick** [comment]
> Strange, I have the same setup (I am pretty sure same Luma version as well). Probably would be best to ask on the discord server.

Well I didn't specify before but when I made this issue I was connected to an iPhone hotspot, connecting to normal wi-fi appeared to fix this issue. Idk probably not important for now, but it's still technically an issue so I'll leave it open ig

**Comment by erievs** [comment]
> > Strange, I have the same setup (I am pretty sure same Luma version as well). Probably would be best to ask on the discord server.
> 
> Well I didn't specify before but when I made this issue I was connected to an iPhone hotspot, connecting to normal wi-fi appeared to fix this issue. Idk probably not important for now, but it's still technically an issue so I'll leave it open ig

It's not an issue then, you should have closed it.
