### ISSUE TITLE
Watch History doesn't work

### ISSUE THREAD

**Issue by 2b-zipper** [erievs/FourthTube#5]
Doesn't work even if Watch History is enabled.
## Screenshots
![00000](https://github.com/user-attachments/assets/fa022521-d20a-428b-9b37-5059da7d24f2)
![00001](https://github.com/user-attachments/assets/b7ba39ba-fd16-43e1-aa17-7f11f9e0cee7)

**Comment by erievs** [comment]
Beta 18 should fix it (I credited you), I need to test it though to see if I did it right.

**Comment by erievs** [comment]
Fixed!
