### ISSUE TITLE
Audio Stuttering at 480p

### ISSUE THREAD

**Issue by RobberyB** [erievs/FourthTube#50]
Whenever I switch to 480p on 2dsXL, audio seems to stutter indefinitely unless the video is left to buffer for around a minute.

**Comment by LuMariGames** [comment]
SELECTボタンを押しながら電源を入れるとconfiguration画面に行きますが、
 - [x] Redirect app. syscore threads to core2
にすると恐らく480p再生が出来るかも知れません。

If you turn on the power while pressing the SELECT button, you will go to the configuration screen, and if you set it to , 
 - [x] Redirect app. syscore threads to core2
you will probably be able to play in 480p.

**Comment by erievs** [comment]
Read above message, fixed/won't fix/not an real issue  idk what I'd call this
