### ISSUE TITLE
Please submit this app to Universal-DB

### ISSUE THREAD

**Issue by udanfacy22** [erievs/FourthTube#51]
[Universal-Updater](https://universal-team.net/projects/universal-updater) is sort of like an app store for DS & 3DS homebrew. It makes it easier for users to discover software and keep them all up-to-date from one central place. [Universal-DB](https://github.com/Universal-Team/db/issues/new?assignees=&labels=app+request&template=app-request.yml) is its default repository.

ThirdTube is currently listed on there, but obviously that hasn't worked in some time.

**Comment by erievs** [comment]
Already done? We just never got approved, please check before submitting issues.
