### ISSUE TITLE
Please add a way to dim or disable the bottom screen during video playback

### ISSUE THREAD

**Issue by udanfacy22** [erievs/FourthTube#52]
It could either be a button on the bottom screen or an option to automatically dim or disable only the bottom screen after some user configurable amount of time. The user could then turn the screen back on simply by touching it or perhaps by pressing a button.

I thought the "[ ]" looking button at the bottom right might possibly do this, since it resembles YouTube's fullscreen button, but nothing happens when I tap it. The "time to turn off the LCD" setting turns off both screens (handy for when you're only listening instead of watching). The "LCD brightness" setting doesn't appear to do anything. If it matters, I use a New 3DS XL.

**Comment by erievs** [comment]
Not really interested as the "time to turn off the LCD" exists.

**Comment by udanfacy22** [comment]
That turns off *both* screens, so you can't see the video. The purpose of my suggestion is to be able to watch the video without the distraction of the bottom screen.
